### PR TITLE
*: repoint go import path to flatcar-linux

### PR DESCRIPTION
**Pull request by vbatts**
To ensure this repo is building from itself, and not relying on a
directory path work-around.

Signed-off-by: Vincent Batts <vbatts@kinvolk.io>

# point the import path this repo

# How to use

clone the repo, run `make`, ensure you have `./bin/locksmithctl`

# Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

### CODE REVIEW

**Review by invidian — APPROVED** [review]
LGTM, perhaps we should migrate to Go modules as well.

**Comment by vbatts** [comment]
@invidian probably a fine thing to do

**Comment by invidian** [comment]
@vbatts I created #3 to track it, as it's not really required for this PR to be merged, I didn't want to put more work on you :) But can be done in this PR as well :smile:

**Comment by vbatts** [comment]
separate PR :joy_cat:

**Pull request merged**
