### PR TITLE
Convert to Go module

### PR DESCRIPTION
**Pull request by dmlambea**
# Convert locksmith project from Glide to a Go modules

Go modules are the official dependency management strategy, so Glide is no longer required. Additionally, the 'vendor' directory can be deleted.

# How to use

Run `go mod tidy` to check the module's dependencies.

# Testing done

Checked the module compilation, but there is still a bug to fix (in a latter PR). Please refer to #3 for more info on this.

### CODE REVIEW

**Comment by pothos** [comment]
Hello,

thanks for your contribution. Just a quick comment, please keep the `vendor` folder and change the `Makefile` to update it (`go mod vendor`). We need the `vendor` folder in Flatcar's build system. Thanks!

I haven't reviewed the actual changes yet and if they work.

**Comment by dmlambea** [comment]
@pothos , the changes have been applied. Please take into account when reviewing that the 'object' field in updateengine/client.go will make the compilation to fail.

**Comment by pothos** [comment]
`make vendor` doesn't work for me, showing this error:
```
go: go.etcd.io/bbolt@v1.3.4 used for two different module paths (github.com/coreos/bbolt and go.etcd.io/bbolt)
```
Also `gopath` is still used in the Makefile but should go since we use modules, or?
Ideally, I would like the `vendor` folder not being updated in this PR – the `glide.lock`/`glide.yaml` files refer to specific revisions which should be used in `go.sum`/`go.mod` which I think will also solve the compilation error you mention (and helps not to break locksmith because of unknown changes in dependency behaviour).

**Comment by pothos** [comment]
I managed to use the the old versions, see this branch:
https://github.com/flatcar-linux/locksmith/tree/kai/go-mod

By the way, linking fails for me but that also happens on `flatcar-master`:
```
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
```

**Comment by dmlambea** [comment]
@pothos, I've merged your patches from kai's and cleaned the remaining gopath-related lines in both Makefile and scripts/test files.

Although it shows some warning of static-linking against glibc, it now compiles properly.

**Comment by pothos** [comment]
Nice, I will have a look, thanks!

The binary won't be statically linked in the end, at least in the way we build it for Flatcar:
```
core@localhost ~ $ ldd /usr/lib64/locksmith/locksmithd
	linux-vdso.so.1 (0x00007ffd6a790000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f65931ef000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6593017000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f659321d000)
core@localhost ~ $ ldd /usr/bin/locksmithctl
	linux-vdso.so.1 (0x00007ffc559e7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f433f7e4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f433f60c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f433f812000)
```
Before we can merge it, I'll have to build a Flatcar version with your changes and let it pass the test suite.

**Comment by pothos** [comment]
One tiny thing to `git apply` which I forgot in my branch:
```
diff --git a/scripts/test b/scripts/test
index dd7366c..52cb87a 100755
--- a/scripts/test
+++ b/scripts/test
@@ -4,7 +4,7 @@ ORG_PATH="github.com/coreos"
 REPO_PATH="${ORG_PATH}/locksmith"
 
 PKGS=$(go list ./... | grep -v vendor)
-FMT_DIRS=$(ls -d */ | grep -v vendor)
+FMT_DIRS=$(ls -d */ | grep -v vendor | grep -v ^etcd)
 LINTABLE=$(go list ./... | grep -v vendor)
 
 echo "Running tests..."
```

**Comment by pothos** [comment]
For me it compiles only with the `-static` link option removed.
```
diff --git a/Makefile b/Makefile
index ab92e83..605823e 100644
--- a/Makefile
+++ b/Makefile
@@ -11,7 +11,7 @@ endif
 
 VERSION=$(shell git describe --dirty)
 REPO=github.com/flatcar-linux/locksmith
-LD_FLAGS="-w -s -extldflags -static"
+LD_FLAGS="-w -s"
 
 export GOPATH=$(shell pwd)/gopath
 

```

**Comment by pothos** [comment]
I added three commits in https://github.com/flatcar-linux/locksmith/tree/kai/go-mod-and-fixups on top of your branch which make it compile for me and pass the tests.

**Comment by pothos** [comment]
Tested it with a Flatcar VM and it works. Please take the last three commits from my new branch and then squash all commits into one but with a longer git message that explains that we had to keep a copy of etcd where we patched the import path, and that the other changes are done to have `make test` and compilation pass again.

**Comment by dmlambea** [comment]
@pothos, I merged before receiving your last comment.

Would it work for you if I push an empty commit with just a message like that you wanted?

**Comment by pothos** [comment]
Can you please squash them and then enter a summary?
```
git reset flatcar-master
git add -A
git commit
git diff origin/go-module # this should be an empty diff
git push --force
```

**Review by pothos — APPROVED** [review]
Thanks a lot for all the cleanup work, also with the new `go list` changes, wonderful :)

**Comment by dmlambea** [comment]
Hi, @pothos !  Thank you for helping me in contributing to Flatcar.

Just a question that is still bouncing in my mind, out of curiosity. You wrote:

> ... We need the `vendor` folder in Flatcar's build system. Thanks!

Why such a "need"? I mean, does the build system reference or use the vendor folder?

**Comment by pothos** [comment]
Fetching remote sources during the build is not allowed by Gentoo's emerge. And it's a good way to ensure reproducibility ;)

**Pull request merged**
